class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'sayu'
        self.UnzipMirrorCommand = 'sayuunzip'
        self.TarMirrorCommand = 'sayutar'
        self.CancelMirror = 'sayucancel'
        self.CancelAllCommand = 'sayucancelall'
        self.ListCommand = 'sayulist'
        self.StatusCommand = 'sayustatus'
        self.AuthorizeCommand = 'auth'
        self.UnAuthorizeCommand = 'unauth'
        self.AuthListCommand = 'authlist'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'sayuclone'
        self.WatchCommand = 'yt'
        self.TarWatchCommand = 'yttar'
        self.DeleteCommand = 'del'
        self.UsageCommand = 'usage'
        self.OwnerCommand = 'owner'

BotCommands = _BotCommands()
